package Vista;

import Datos.Personal;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import rsbuttom.CambiaPanel;

public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    private Personal objP = null;
    private CambiaPanel cambiar = new CambiaPanel();

    public frmPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        setIconImage(getIconImage());

        this.btnProducto.setSelected(true);

        cambiar = new CambiaPanel(content, new panelProducto(), 1188, 570);
    }

    @Override
    public Image getIconImage() {
        Image image = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/logo.png"));
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnProducto = new rsbuttom.RSButtonMetro();
        btnUnidadMedida = new rsbuttom.RSButtonMetro();
        btnSalidaProducto = new rsbuttom.RSButtonMetro();
        btnCategoria = new rsbuttom.RSButtonMetro();
        btnMarca = new rsbuttom.RSButtonMetro();
        btnProveedor = new rsbuttom.RSButtonMetro();
        btnReporteDiario = new rsbuttom.RSButtonMetro();
        btnCompra = new rsbuttom.RSButtonMetro();
        btnReporteSemanal = new rsbuttom.RSButtonMetro();
        btnReporteMensual = new rsbuttom.RSButtonMetro();
        panelContenido = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CENTRO DE DESARROLLO INTEGRAL DE LA FAMILIA - BAGUA");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        panelMenu.setBackground(new java.awt.Color(255, 153, 153));
        panelMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(239, 238, 244)));

        jPanel5.setBackground(new java.awt.Color(255, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo2.png"))); // NOI18N
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        btnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estar.png"))); // NOI18N
        btnProducto.setText("PRODUCTO");
        btnProducto.setColorHover(new java.awt.Color(255, 102, 102));
        btnProducto.setColorNormal(new java.awt.Color(255, 102, 102));
        btnProducto.setColorPressed(new java.awt.Color(255, 102, 102));
        btnProducto.setColorTextHover(new java.awt.Color(0, 0, 0));
        btnProducto.setColorTextNormal(new java.awt.Color(0, 0, 0));
        btnProducto.setColorTextPressed(new java.awt.Color(0, 0, 0));
        btnProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProducto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnProducto.setIconTextGap(25);
        btnProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProductoMousePressed(evt);
            }
        });
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });

        btnUnidadMedida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/equilibrio.png"))); // NOI18N
        btnUnidadMedida.setText("UNIDAD DE MEDIDA");
        btnUnidadMedida.setColorHover(new java.awt.Color(255, 102, 102));
        btnUnidadMedida.setColorNormal(new java.awt.Color(255, 153, 153));
        btnUnidadMedida.setColorPressed(new java.awt.Color(255, 102, 102));
        btnUnidadMedida.setColorTextHover(new java.awt.Color(0, 0, 0));
        btnUnidadMedida.setColorTextNormal(new java.awt.Color(0, 0, 0));
        btnUnidadMedida.setColorTextPressed(new java.awt.Color(0, 0, 0));
        btnUnidadMedida.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUnidadMedida.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnUnidadMedida.setIconTextGap(25);
        btnUnidadMedida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUnidadMedidaMousePressed(evt);
            }
        });
        btnUnidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnidadMedidaActionPerformed(evt);
            }
        });

        btnSalidaProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salidaProducto.png"))); // NOI18N
        btnSalidaProducto.setText("SALIDA PRODUCTOS");
        btnSalidaProducto.setColorHover(new java.awt.Color(255, 102, 102));
        btnSalidaProducto.setColorNormal(new java.awt.Color(255, 153, 153));
        btnSalidaProducto.setColorPressed(new java.awt.Color(255, 102, 102));
        btnSalidaProducto.setColorTextHover(new java.awt.Color(0, 0, 0));
        btnSalidaProducto.setColorTextNormal(new java.awt.Color(0, 0, 0));
        btnSalidaProducto.setColorTextPressed(new java.awt.Color(0, 0, 0));
        btnSalidaProducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSalidaProducto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSalidaProducto.setIconTextGap(25);
        btnSalidaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSalidaProductoMousePressed(evt);
            }
        });
        btnSalidaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaProductoActionPerformed(evt);
            }
        });

        btnCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aplicacion.png"))); // NOI18N
        btnCategoria.setText("CATEGORÍA");
        btnCategoria.setColorHover(new java.awt.Color(255, 102, 102));
        btnCategoria.setColorNormal(new java.awt.Color(255, 153, 153));
        btnCategoria.setColorPressed(new java.awt.Color(255, 102, 102));
        btnCategoria.setColorTextHover(new java.awt.Color(0, 0, 0));
        btnCategoria.setColorTextNormal(new java.awt.Color(0, 0, 0));
        btnCategoria.setColorTextPressed(new java.awt.Color(0, 0, 0));
        btnCategoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCategoria.setIconTextGap(25);
        btnCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCategoriaMousePressed(evt);
            }
        });
        btnCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriaActionPerformed(evt);
            }
        });

        btnMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/marca.png"))); // NOI18N
        btnMarca.setText("MARCA");
        btnMarca.setColorHover(new java.awt.Color(255, 102, 102));
        btnMarca.setColorNormal(new java.awt.Color(255, 153, 153));
        btnMarca.setColorPressed(new java.awt.Color(255, 102, 102));
        btnMarca.setColorTextHover(new java.awt.Color(0, 0, 0));
        btnMarca.setColorTextNormal(new java.awt.Color(0, 0, 0));
        btnMarca.setColorTextPressed(new java.awt.Color(0, 0, 0));
        btnMarca.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMarca.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMarca.setIconTextGap(25);
        btnMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMarcaMousePressed(evt);
            }
        });
        btnMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcaActionPerformed(evt);
            }
        });

        btnProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proveedor.png"))); // NOI18N
        btnProveedor.setText("PROVEEDOR");
        btnProveedor.setColorHover(new java.awt.Color(255, 102, 102));
        btnProveedor.setColorNormal(new java.awt.Color(255, 153, 153));
        btnProveedor.setColorPressed(new java.awt.Color(255, 102, 102));
        btnProveedor.setColorTextHover(new java.awt.Color(0, 0, 0));
        btnProveedor.setColorTextNormal(new java.awt.Color(0, 0, 0));
        btnProveedor.setColorTextPressed(new java.awt.Color(0, 0, 0));
        btnProveedor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProveedor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnProveedor.setIconTextGap(25);
        btnProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProveedorMousePressed(evt);
            }
        });
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });

        btnReporteDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporte-diario.png"))); // NOI18N
        btnReporteDiario.setText("REPORTES DIARIOS");
        btnReporteDiario.setColorHover(new java.awt.Color(255, 102, 102));
        btnReporteDiario.setColorNormal(new java.awt.Color(255, 153, 153));
        btnReporteDiario.setColorPressed(new java.awt.Color(255, 102, 102));
        btnReporteDiario.setColorTextHover(new java.awt.Color(0, 0, 0));
        btnReporteDiario.setColorTextNormal(new java.awt.Color(0, 0, 0));
        btnReporteDiario.setColorTextPressed(new java.awt.Color(0, 0, 0));
        btnReporteDiario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReporteDiario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnReporteDiario.setIconTextGap(25);
        btnReporteDiario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnReporteDiarioMousePressed(evt);
            }
        });
        btnReporteDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteDiarioActionPerformed(evt);
            }
        });

        btnCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/productos.png"))); // NOI18N
        btnCompra.setText("COMPRA");
        btnCompra.setColorHover(new java.awt.Color(255, 102, 102));
        btnCompra.setColorNormal(new java.awt.Color(255, 153, 153));
        btnCompra.setColorPressed(new java.awt.Color(255, 102, 102));
        btnCompra.setColorTextHover(new java.awt.Color(0, 0, 0));
        btnCompra.setColorTextNormal(new java.awt.Color(0, 0, 0));
        btnCompra.setColorTextPressed(new java.awt.Color(0, 0, 0));
        btnCompra.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCompra.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCompra.setIconTextGap(25);
        btnCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCompraMousePressed(evt);
            }
        });
        btnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraActionPerformed(evt);
            }
        });

        btnReporteSemanal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/notas.png"))); // NOI18N
        btnReporteSemanal.setText("REPORTES SEMANALES");
        btnReporteSemanal.setColorHover(new java.awt.Color(255, 102, 102));
        btnReporteSemanal.setColorNormal(new java.awt.Color(255, 153, 153));
        btnReporteSemanal.setColorPressed(new java.awt.Color(255, 102, 102));
        btnReporteSemanal.setColorTextHover(new java.awt.Color(0, 0, 0));
        btnReporteSemanal.setColorTextNormal(new java.awt.Color(0, 0, 0));
        btnReporteSemanal.setColorTextPressed(new java.awt.Color(0, 0, 0));
        btnReporteSemanal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReporteSemanal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnReporteSemanal.setIconTextGap(25);
        btnReporteSemanal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnReporteSemanalMousePressed(evt);
            }
        });
        btnReporteSemanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteSemanalActionPerformed(evt);
            }
        });

        btnReporteMensual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporte-mensual.png"))); // NOI18N
        btnReporteMensual.setText("REPORTES MENSUALES");
        btnReporteMensual.setColorHover(new java.awt.Color(255, 102, 102));
        btnReporteMensual.setColorNormal(new java.awt.Color(255, 153, 153));
        btnReporteMensual.setColorPressed(new java.awt.Color(255, 102, 102));
        btnReporteMensual.setColorTextHover(new java.awt.Color(0, 0, 0));
        btnReporteMensual.setColorTextNormal(new java.awt.Color(0, 0, 0));
        btnReporteMensual.setColorTextPressed(new java.awt.Color(0, 0, 0));
        btnReporteMensual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReporteMensual.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnReporteMensual.setIconTextGap(25);
        btnReporteMensual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnReporteMensualMousePressed(evt);
            }
        });
        btnReporteMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteMensualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReporteSemanal, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalidaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReporteDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReporteMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalidaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReporteDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReporteSemanal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReporteMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jScrollPane2.setViewportView(jPanel5);

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 8.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        jPanel1.add(panelMenu, gridBagConstraints);

        panelContenido.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(null);

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 835, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1063, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(content);

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(panelContenido, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
        cambiar = new CambiaPanel(content, new panelProducto(), 1188, 570);

        if (this.btnProducto.isSelected()) {
            this.btnProducto.setColorNormal(new Color(255, 102, 102));
            this.btnProducto.setColorHover(new Color(255, 102, 102));
            this.btnProducto.setColorPressed(new Color(255, 102, 102));

            this.btnProveedor.setColorNormal(new Color(255, 153, 153));
            this.btnProveedor.setColorHover(new Color(255, 102, 102));
            this.btnProveedor.setColorPressed(new Color(255, 102, 102));

            this.btnMarca.setColorNormal(new Color(255, 153, 153));
            this.btnMarca.setColorHover(new Color(255, 102, 102));
            this.btnMarca.setColorPressed(new Color(255, 102, 102));

            this.btnCategoria.setColorNormal(new Color(255, 153, 153));
            this.btnCategoria.setColorHover(new Color(255, 102, 102));
            this.btnCategoria.setColorPressed(new Color(255, 102, 102));

            this.btnUnidadMedida.setColorNormal(new Color(255, 153, 153));
            this.btnUnidadMedida.setColorHover(new Color(255, 102, 102));
            this.btnUnidadMedida.setColorPressed(new Color(255, 102, 102));

            this.btnCompra.setColorNormal(new Color(255, 153, 153));
            this.btnCompra.setColorHover(new Color(255, 102, 102));
            this.btnCompra.setColorPressed(new Color(255, 102, 102));

            this.btnSalidaProducto.setColorNormal(new Color(255, 153, 153));
            this.btnSalidaProducto.setColorHover(new Color(255, 102, 102));
            this.btnSalidaProducto.setColorPressed(new Color(255, 102, 102));

            this.btnReporteDiario.setColorNormal(new Color(255, 153, 153));
            this.btnReporteDiario.setColorHover(new Color(255, 102, 102));
            this.btnReporteDiario.setColorPressed(new Color(255, 102, 102));
            
            this.btnReporteMensual.setColorNormal(new Color(255, 153, 153));
            this.btnReporteMensual.setColorHover(new Color(255, 102, 102));
            this.btnReporteMensual.setColorPressed(new Color(255, 102, 102));
            
            this.btnReporteSemanal.setColorNormal(new Color(255, 153, 153));
            this.btnReporteSemanal.setColorHover(new Color(255, 102, 102));
            this.btnReporteSemanal.setColorPressed(new Color(255, 102, 102));
        } else {
            this.btnProducto.setColorNormal(new Color(255, 153, 153));
            this.btnProducto.setColorHover(new Color(255, 102, 102));
            this.btnProducto.setColorPressed(new Color(255, 102, 102));
        }
    }//GEN-LAST:event_btnProductoActionPerformed

    private void btnProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductoMousePressed
        this.btnProducto.setSelected(true);
        this.btnProveedor.setSelected(false);
        this.btnMarca.setSelected(false);
        this.btnCategoria.setSelected(false);
        this.btnUnidadMedida.setSelected(false);
        this.btnCompra.setSelected(false);
        this.btnSalidaProducto.setSelected(false);
        this.btnReporteDiario.setSelected(false);
        this.btnReporteMensual.setSelected(false);
        this.btnReporteSemanal.setSelected(false);
    }//GEN-LAST:event_btnProductoMousePressed

    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        cambiar = new CambiaPanel(content, new panelProveedor(), 1144, 535);

        if (this.btnProveedor.isSelected()) {
            this.btnProducto.setColorNormal(new Color(255, 153, 153));
            this.btnProducto.setColorHover(new Color(255, 102, 102));
            this.btnProducto.setColorPressed(new Color(255, 102, 102));

            this.btnProveedor.setColorNormal(new Color(255, 102, 102));
            this.btnProveedor.setColorHover(new Color(255, 102, 102));
            this.btnProveedor.setColorPressed(new Color(255, 102, 102));

            this.btnMarca.setColorNormal(new Color(255, 153, 153));
            this.btnMarca.setColorHover(new Color(255, 102, 102));
            this.btnMarca.setColorPressed(new Color(255, 102, 102));

            this.btnCategoria.setColorNormal(new Color(255, 153, 153));
            this.btnCategoria.setColorHover(new Color(255, 102, 102));
            this.btnCategoria.setColorPressed(new Color(255, 102, 102));

            this.btnUnidadMedida.setColorNormal(new Color(255, 153, 153));
            this.btnUnidadMedida.setColorHover(new Color(255, 102, 102));
            this.btnUnidadMedida.setColorPressed(new Color(255, 102, 102));

            this.btnCompra.setColorNormal(new Color(255, 153, 153));
            this.btnCompra.setColorHover(new Color(255, 102, 102));
            this.btnCompra.setColorPressed(new Color(255, 102, 102));

            this.btnSalidaProducto.setColorNormal(new Color(255, 153, 153));
            this.btnSalidaProducto.setColorHover(new Color(255, 102, 102));
            this.btnSalidaProducto.setColorPressed(new Color(255, 102, 102));

            this.btnReporteDiario.setColorNormal(new Color(255, 153, 153));
            this.btnReporteDiario.setColorHover(new Color(255, 102, 102));
            this.btnReporteDiario.setColorPressed(new Color(255, 102, 102));
            
            this.btnReporteMensual.setColorNormal(new Color(255, 153, 153));
            this.btnReporteMensual.setColorHover(new Color(255, 102, 102));
            this.btnReporteMensual.setColorPressed(new Color(255, 102, 102));
            
            this.btnReporteSemanal.setColorNormal(new Color(255, 153, 153));
            this.btnReporteSemanal.setColorHover(new Color(255, 102, 102));
            this.btnReporteSemanal.setColorPressed(new Color(255, 102, 102));
        } else {
            this.btnProveedor.setColorNormal(new Color(255, 153, 153));
            this.btnProveedor.setColorHover(new Color(255, 102, 102));
            this.btnProveedor.setColorPressed(new Color(255, 102, 102));
        }
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriaActionPerformed
        cambiar = new CambiaPanel(content, new panelCategoria(), 964, 450);

        if (this.btnCategoria.isSelected()) {
            this.btnProducto.setColorNormal(new Color(255, 153, 153));
            this.btnProducto.setColorHover(new Color(255, 102, 102));
            this.btnProducto.setColorPressed(new Color(255, 102, 102));

            this.btnProveedor.setColorNormal(new Color(255, 153, 153));
            this.btnProveedor.setColorHover(new Color(255, 102, 102));
            this.btnProveedor.setColorPressed(new Color(255, 102, 102));

            this.btnMarca.setColorNormal(new Color(255, 153, 153));
            this.btnMarca.setColorHover(new Color(255, 102, 102));
            this.btnMarca.setColorPressed(new Color(255, 102, 102));

            this.btnCategoria.setColorNormal(new Color(255, 102, 102));
            this.btnCategoria.setColorHover(new Color(255, 102, 102));
            this.btnCategoria.setColorPressed(new Color(255, 102, 102));

            this.btnUnidadMedida.setColorNormal(new Color(255, 153, 153));
            this.btnUnidadMedida.setColorHover(new Color(255, 102, 102));
            this.btnUnidadMedida.setColorPressed(new Color(255, 102, 102));

            this.btnCompra.setColorNormal(new Color(255, 153, 153));
            this.btnCompra.setColorHover(new Color(255, 102, 102));
            this.btnCompra.setColorPressed(new Color(255, 102, 102));

            this.btnSalidaProducto.setColorNormal(new Color(255, 153, 153));
            this.btnSalidaProducto.setColorHover(new Color(255, 102, 102));
            this.btnSalidaProducto.setColorPressed(new Color(255, 102, 102));

            this.btnReporteDiario.setColorNormal(new Color(255, 153, 153));
            this.btnReporteDiario.setColorHover(new Color(255, 102, 102));
            this.btnReporteDiario.setColorPressed(new Color(255, 102, 102));
            
            this.btnReporteMensual.setColorNormal(new Color(255, 153, 153));
            this.btnReporteMensual.setColorHover(new Color(255, 102, 102));
            this.btnReporteMensual.setColorPressed(new Color(255, 102, 102));
            
            this.btnReporteSemanal.setColorNormal(new Color(255, 153, 153));
            this.btnReporteSemanal.setColorHover(new Color(255, 102, 102));
            this.btnReporteSemanal.setColorPressed(new Color(255, 102, 102));
            
        } else {
            this.btnCategoria.setColorNormal(new Color(255, 153, 153));
            this.btnCategoria.setColorHover(new Color(255, 102, 102));
            this.btnCategoria.setColorPressed(new Color(255, 102, 102));
        }
    }//GEN-LAST:event_btnCategoriaActionPerformed

    private void btnCategoriaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategoriaMousePressed
        this.btnProducto.setSelected(false);
        this.btnProveedor.setSelected(false);
        this.btnMarca.setSelected(false);
        this.btnCategoria.setSelected(true);
        this.btnUnidadMedida.setSelected(false);
        this.btnCompra.setSelected(false);
        this.btnSalidaProducto.setSelected(false);
        this.btnReporteDiario.setSelected(false);
        this.btnReporteMensual.setSelected(false);
        this.btnReporteSemanal.setSelected(false);
    }//GEN-LAST:event_btnCategoriaMousePressed

    private void btnProveedorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedorMousePressed
        this.btnProducto.setSelected(false);
        this.btnProveedor.setSelected(true);
        this.btnMarca.setSelected(false);
        this.btnCategoria.setSelected(false);
        this.btnUnidadMedida.setSelected(false);
        this.btnCompra.setSelected(false);
        this.btnSalidaProducto.setSelected(false);
        this.btnReporteDiario.setSelected(false);
        this.btnReporteMensual.setSelected(false);
        this.btnReporteSemanal.setSelected(false);
    }//GEN-LAST:event_btnProveedorMousePressed

    private void btnMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcaActionPerformed
        cambiar = new CambiaPanel(content, new panelMarca(), 956, 460);

        if (this.btnMarca.isSelected()) {
            this.btnProducto.setColorNormal(new Color(255, 153, 153));
            this.btnProducto.setColorHover(new Color(255, 102, 102));
            this.btnProducto.setColorPressed(new Color(255, 102, 102));

            this.btnProveedor.setColorNormal(new Color(255, 153, 153));
            this.btnProveedor.setColorHover(new Color(255, 102, 102));
            this.btnProveedor.setColorPressed(new Color(255, 102, 102));

            this.btnMarca.setColorNormal(new Color(255, 102, 102));
            this.btnMarca.setColorHover(new Color(255, 102, 102));
            this.btnMarca.setColorPressed(new Color(255, 102, 102));

            this.btnCategoria.setColorNormal(new Color(255, 153, 153));
            this.btnCategoria.setColorHover(new Color(255, 102, 102));
            this.btnCategoria.setColorPressed(new Color(255, 102, 102));

            this.btnUnidadMedida.setColorNormal(new Color(255, 153, 153));
            this.btnUnidadMedida.setColorHover(new Color(255, 102, 102));
            this.btnUnidadMedida.setColorPressed(new Color(255, 102, 102));

            this.btnCompra.setColorNormal(new Color(255, 153, 153));
            this.btnCompra.setColorHover(new Color(255, 102, 102));
            this.btnCompra.setColorPressed(new Color(255, 102, 102));

            this.btnSalidaProducto.setColorNormal(new Color(255, 153, 153));
            this.btnSalidaProducto.setColorHover(new Color(255, 102, 102));
            this.btnSalidaProducto.setColorPressed(new Color(255, 102, 102));

            this.btnReporteDiario.setColorNormal(new Color(255, 153, 153));
            this.btnReporteDiario.setColorHover(new Color(255, 102, 102));
            this.btnReporteDiario.setColorPressed(new Color(255, 102, 102));
            
            this.btnReporteMensual.setColorNormal(new Color(255, 153, 153));
            this.btnReporteMensual.setColorHover(new Color(255, 102, 102));
            this.btnReporteMensual.setColorPressed(new Color(255, 102, 102));
            
            this.btnReporteSemanal.setColorNormal(new Color(255, 153, 153));
            this.btnReporteSemanal.setColorHover(new Color(255, 102, 102));
            this.btnReporteSemanal.setColorPressed(new Color(255, 102, 102));
        } else {
            this.btnMarca.setColorNormal(new Color(255, 153, 153));
            this.btnMarca.setColorHover(new Color(255, 102, 102));
            this.btnMarca.setColorPressed(new Color(255, 102, 102));
        }
    }//GEN-LAST:event_btnMarcaActionPerformed

    private void btnMarcaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMarcaMousePressed
        this.btnProducto.setSelected(false);
        this.btnProveedor.setSelected(false);
        this.btnMarca.setSelected(true);
        this.btnCategoria.setSelected(false);
        this.btnUnidadMedida.setSelected(false);
        this.btnCompra.setSelected(false);
        this.btnSalidaProducto.setSelected(false);
        this.btnReporteDiario.setSelected(false);
        this.btnReporteMensual.setSelected(false);
        this.btnReporteSemanal.setSelected(false);
    }//GEN-LAST:event_btnMarcaMousePressed

    private void btnUnidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnidadMedidaActionPerformed
        cambiar = new CambiaPanel(content, new panelUnidadMedida(), 992, 465);

        if (this.btnUnidadMedida.isSelected()) {
            this.btnProducto.setColorNormal(new Color(255, 153, 153));
            this.btnProducto.setColorHover(new Color(255, 102, 102));
            this.btnProducto.setColorPressed(new Color(255, 102, 102));

            this.btnProveedor.setColorNormal(new Color(255, 153, 153));
            this.btnProveedor.setColorHover(new Color(255, 102, 102));
            this.btnProveedor.setColorPressed(new Color(255, 102, 102));

            this.btnMarca.setColorNormal(new Color(255, 153, 153));
            this.btnMarca.setColorHover(new Color(255, 102, 102));
            this.btnMarca.setColorPressed(new Color(255, 102, 102));

            this.btnCategoria.setColorNormal(new Color(255, 153, 153));
            this.btnCategoria.setColorHover(new Color(255, 102, 102));
            this.btnCategoria.setColorPressed(new Color(255, 102, 102));

            this.btnUnidadMedida.setColorNormal(new Color(255, 102, 102));
            this.btnUnidadMedida.setColorHover(new Color(255, 102, 102));
            this.btnUnidadMedida.setColorPressed(new Color(255, 102, 102));

            this.btnCompra.setColorNormal(new Color(255, 153, 153));
            this.btnCompra.setColorHover(new Color(255, 102, 102));
            this.btnCompra.setColorPressed(new Color(255, 102, 102));

            this.btnSalidaProducto.setColorNormal(new Color(255, 153, 153));
            this.btnSalidaProducto.setColorHover(new Color(255, 102, 102));
            this.btnSalidaProducto.setColorPressed(new Color(255, 102, 102));

            this.btnReporteDiario.setColorNormal(new Color(255, 153, 153));
            this.btnReporteDiario.setColorHover(new Color(255, 102, 102));
            this.btnReporteDiario.setColorPressed(new Color(255, 102, 102));
            
            this.btnReporteMensual.setColorNormal(new Color(255, 153, 153));
            this.btnReporteMensual.setColorHover(new Color(255, 102, 102));
            this.btnReporteMensual.setColorPressed(new Color(255, 102, 102));
            
            this.btnReporteSemanal.setColorNormal(new Color(255, 153, 153));
            this.btnReporteSemanal.setColorHover(new Color(255, 102, 102));
            this.btnReporteSemanal.setColorPressed(new Color(255, 102, 102));
        } else {
            this.btnUnidadMedida.setColorNormal(new Color(255, 153, 153));
            this.btnUnidadMedida.setColorHover(new Color(255, 102, 102));
            this.btnUnidadMedida.setColorPressed(new Color(255, 102, 102));
        }
    }//GEN-LAST:event_btnUnidadMedidaActionPerformed

    private void btnUnidadMedidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUnidadMedidaMousePressed
        this.btnProducto.setSelected(false);
        this.btnProveedor.setSelected(false);
        this.btnMarca.setSelected(false);
        this.btnCategoria.setSelected(false);
        this.btnUnidadMedida.setSelected(true);
        this.btnCompra.setSelected(false);
        this.btnSalidaProducto.setSelected(false);
        this.btnReporteDiario.setSelected(false);
        this.btnReporteMensual.setSelected(false);
        this.btnReporteSemanal.setSelected(false);
    }//GEN-LAST:event_btnUnidadMedidaMousePressed

    private void btnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraActionPerformed
        cambiar = new CambiaPanel(content, new panelCompra(this.objP), 1485, 780);

        if (this.btnCompra.isSelected()) {
            this.btnProducto.setColorNormal(new Color(255, 153, 153));
            this.btnProducto.setColorHover(new Color(255, 102, 102));
            this.btnProducto.setColorPressed(new Color(255, 102, 102));

            this.btnProveedor.setColorNormal(new Color(255, 153, 153));
            this.btnProveedor.setColorHover(new Color(255, 102, 102));
            this.btnProveedor.setColorPressed(new Color(255, 102, 102));

            this.btnMarca.setColorNormal(new Color(255, 153, 153));
            this.btnMarca.setColorHover(new Color(255, 102, 102));
            this.btnMarca.setColorPressed(new Color(255, 102, 102));

            this.btnCategoria.setColorNormal(new Color(255, 153, 153));
            this.btnCategoria.setColorHover(new Color(255, 102, 102));
            this.btnCategoria.setColorPressed(new Color(255, 102, 102));

            this.btnUnidadMedida.setColorNormal(new Color(255, 153, 153));
            this.btnUnidadMedida.setColorHover(new Color(255, 102, 102));
            this.btnUnidadMedida.setColorPressed(new Color(255, 102, 102));

            this.btnCompra.setColorNormal(new Color(255, 102, 102));
            this.btnCompra.setColorHover(new Color(255, 102, 102));
            this.btnCompra.setColorPressed(new Color(255, 102, 102));

            this.btnSalidaProducto.setColorNormal(new Color(255, 153, 153));
            this.btnSalidaProducto.setColorHover(new Color(255, 102, 102));
            this.btnSalidaProducto.setColorPressed(new Color(255, 102, 102));

            this.btnReporteDiario.setColorNormal(new Color(255, 153, 153));
            this.btnReporteDiario.setColorHover(new Color(255, 102, 102));
            this.btnReporteDiario.setColorPressed(new Color(255, 102, 102));
            
            this.btnReporteMensual.setColorNormal(new Color(255, 153, 153));
            this.btnReporteMensual.setColorHover(new Color(255, 102, 102));
            this.btnReporteMensual.setColorPressed(new Color(255, 102, 102));
            
            this.btnReporteSemanal.setColorNormal(new Color(255, 153, 153));
            this.btnReporteSemanal.setColorHover(new Color(255, 102, 102));
            this.btnReporteSemanal.setColorPressed(new Color(255, 102, 102));
        } else {
            this.btnCompra.setColorNormal(new Color(255, 153, 153));
            this.btnCompra.setColorHover(new Color(255, 102, 102));
            this.btnCompra.setColorPressed(new Color(255, 102, 102));
        }
    }//GEN-LAST:event_btnCompraActionPerformed

    private void btnCompraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompraMousePressed
        this.btnProducto.setSelected(false);
        this.btnProveedor.setSelected(false);
        this.btnMarca.setSelected(false);
        this.btnCategoria.setSelected(false);
        this.btnUnidadMedida.setSelected(false);
        this.btnCompra.setSelected(true);
        this.btnSalidaProducto.setSelected(false);
        this.btnReporteDiario.setSelected(false);
        this.btnReporteMensual.setSelected(false);
        this.btnReporteSemanal.setSelected(false);
    }//GEN-LAST:event_btnCompraMousePressed

    private void btnSalidaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaProductoActionPerformed
        cambiar = new CambiaPanel(content, new panelPrepAlimento(this.objP), 1531, 688);

        if (this.btnSalidaProducto.isSelected()) {
            this.btnProducto.setColorNormal(new Color(255, 153, 153));
            this.btnProducto.setColorHover(new Color(255, 102, 102));
            this.btnProducto.setColorPressed(new Color(255, 102, 102));

            this.btnProveedor.setColorNormal(new Color(255, 153, 153));
            this.btnProveedor.setColorHover(new Color(255, 102, 102));
            this.btnProveedor.setColorPressed(new Color(255, 102, 102));

            this.btnMarca.setColorNormal(new Color(255, 153, 153));
            this.btnMarca.setColorHover(new Color(255, 102, 102));
            this.btnMarca.setColorPressed(new Color(255, 102, 102));

            this.btnCategoria.setColorNormal(new Color(255, 153, 153));
            this.btnCategoria.setColorHover(new Color(255, 102, 102));
            this.btnCategoria.setColorPressed(new Color(255, 102, 102));

            this.btnUnidadMedida.setColorNormal(new Color(255, 153, 153));
            this.btnUnidadMedida.setColorHover(new Color(255, 102, 102));
            this.btnUnidadMedida.setColorPressed(new Color(255, 102, 102));

            this.btnCompra.setColorNormal(new Color(255, 153, 153));
            this.btnCompra.setColorHover(new Color(255, 102, 102));
            this.btnCompra.setColorPressed(new Color(255, 102, 102));

            this.btnSalidaProducto.setColorNormal(new Color(255, 102, 102));
            this.btnSalidaProducto.setColorHover(new Color(255, 102, 102));
            this.btnSalidaProducto.setColorPressed(new Color(255, 102, 102));

            this.btnReporteDiario.setColorNormal(new Color(255, 153, 153));
            this.btnReporteDiario.setColorHover(new Color(255, 102, 102));
            this.btnReporteDiario.setColorPressed(new Color(255, 102, 102));
            
            this.btnReporteMensual.setColorNormal(new Color(255, 153, 153));
            this.btnReporteMensual.setColorHover(new Color(255, 102, 102));
            this.btnReporteMensual.setColorPressed(new Color(255, 102, 102));
            
            this.btnReporteSemanal.setColorNormal(new Color(255, 153, 153));
            this.btnReporteSemanal.setColorHover(new Color(255, 102, 102));
            this.btnReporteSemanal.setColorPressed(new Color(255, 102, 102));
            
        } else {
            this.btnSalidaProducto.setColorNormal(new Color(255, 153, 153));
            this.btnSalidaProducto.setColorHover(new Color(255, 102, 102));
            this.btnSalidaProducto.setColorPressed(new Color(255, 102, 102));
        }
    }//GEN-LAST:event_btnSalidaProductoActionPerformed

    private void btnSalidaProductoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalidaProductoMousePressed
        this.btnProducto.setSelected(false);
        this.btnProveedor.setSelected(false);
        this.btnMarca.setSelected(false);
        this.btnCategoria.setSelected(false);
        this.btnUnidadMedida.setSelected(false);
        this.btnCompra.setSelected(false);
        this.btnSalidaProducto.setSelected(true);
        this.btnReporteDiario.setSelected(false);
        this.btnReporteMensual.setSelected(false);
        this.btnReporteSemanal.setSelected(false);
    }//GEN-LAST:event_btnSalidaProductoMousePressed

    private void btnReporteDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteDiarioActionPerformed
        cambiar = new CambiaPanel(content, new panelReportDiario(), 336, 205);

        if (this.btnReporteDiario.isSelected()) {
            this.btnProducto.setColorNormal(new Color(255, 153, 153));
            this.btnProducto.setColorHover(new Color(255, 102, 102));
            this.btnProducto.setColorPressed(new Color(255, 102, 102));

            this.btnProveedor.setColorNormal(new Color(255, 153, 153));
            this.btnProveedor.setColorHover(new Color(255, 102, 102));
            this.btnProveedor.setColorPressed(new Color(255, 102, 102));

            this.btnMarca.setColorNormal(new Color(255, 153, 153));
            this.btnMarca.setColorHover(new Color(255, 102, 102));
            this.btnMarca.setColorPressed(new Color(255, 102, 102));

            this.btnCategoria.setColorNormal(new Color(255, 153, 153));
            this.btnCategoria.setColorHover(new Color(255, 102, 102));
            this.btnCategoria.setColorPressed(new Color(255, 102, 102));

            this.btnUnidadMedida.setColorNormal(new Color(255, 153, 153));
            this.btnUnidadMedida.setColorHover(new Color(255, 102, 102));
            this.btnUnidadMedida.setColorPressed(new Color(255, 102, 102));

            this.btnCompra.setColorNormal(new Color(255, 153, 153));
            this.btnCompra.setColorHover(new Color(255, 102, 102));
            this.btnCompra.setColorPressed(new Color(255, 102, 102));

            this.btnSalidaProducto.setColorNormal(new Color(255, 153, 153));
            this.btnSalidaProducto.setColorHover(new Color(255, 102, 102));
            this.btnSalidaProducto.setColorPressed(new Color(255, 102, 102));

            this.btnReporteDiario.setColorNormal(new Color(255, 102, 102));
            this.btnReporteDiario.setColorHover(new Color(255, 102, 102));
            this.btnReporteDiario.setColorPressed(new Color(255, 102, 102));
            
            this.btnReporteMensual.setColorNormal(new Color(255, 153, 153));
            this.btnReporteMensual.setColorHover(new Color(255, 102, 102));
            this.btnReporteMensual.setColorPressed(new Color(255, 102, 102));
            
            this.btnReporteSemanal.setColorNormal(new Color(255, 153, 153));
            this.btnReporteSemanal.setColorHover(new Color(255, 102, 102));
            this.btnReporteSemanal.setColorPressed(new Color(255, 102, 102));
        } else {
            this.btnReporteDiario.setColorNormal(new Color(255, 153, 153));
            this.btnReporteDiario.setColorHover(new Color(255, 102, 102));
            this.btnReporteDiario.setColorPressed(new Color(255, 102, 102));
        }
    }//GEN-LAST:event_btnReporteDiarioActionPerformed

    private void btnReporteDiarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteDiarioMousePressed
        this.btnProducto.setSelected(false);
        this.btnProveedor.setSelected(false);
        this.btnMarca.setSelected(false);
        this.btnCategoria.setSelected(false);
        this.btnUnidadMedida.setSelected(false);
        this.btnCompra.setSelected(false);
        this.btnSalidaProducto.setSelected(false);
        this.btnReporteDiario.setSelected(true);
        this.btnReporteMensual.setSelected(false);
        this.btnReporteSemanal.setSelected(false);
    }//GEN-LAST:event_btnReporteDiarioMousePressed

    private void btnReporteSemanalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteSemanalMousePressed
        this.btnProducto.setSelected(false);
        this.btnProveedor.setSelected(false);
        this.btnMarca.setSelected(false);
        this.btnCategoria.setSelected(false);
        this.btnUnidadMedida.setSelected(false);
        this.btnCompra.setSelected(false);
        this.btnSalidaProducto.setSelected(false);
        this.btnReporteDiario.setSelected(false);
        this.btnReporteMensual.setSelected(false);
        this.btnReporteSemanal.setSelected(true);
    }//GEN-LAST:event_btnReporteSemanalMousePressed

    private void btnReporteMensualMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteMensualMousePressed
        this.btnProducto.setSelected(false);
        this.btnProveedor.setSelected(false);
        this.btnMarca.setSelected(false);
        this.btnCategoria.setSelected(false);
        this.btnUnidadMedida.setSelected(false);
        this.btnCompra.setSelected(false);
        this.btnSalidaProducto.setSelected(false);
        this.btnReporteDiario.setSelected(false);
        this.btnReporteMensual.setSelected(true);
        this.btnReporteSemanal.setSelected(false);
    }//GEN-LAST:event_btnReporteMensualMousePressed

    private void btnReporteSemanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteSemanalActionPerformed
        cambiar = new CambiaPanel(content, new panelReportSemanal(), 336, 292);

        if (this.btnReporteSemanal.isSelected()) {
            this.btnProducto.setColorNormal(new Color(255, 153, 153));
            this.btnProducto.setColorHover(new Color(255, 102, 102));
            this.btnProducto.setColorPressed(new Color(255, 102, 102));

            this.btnProveedor.setColorNormal(new Color(255, 153, 153));
            this.btnProveedor.setColorHover(new Color(255, 102, 102));
            this.btnProveedor.setColorPressed(new Color(255, 102, 102));

            this.btnMarca.setColorNormal(new Color(255, 153, 153));
            this.btnMarca.setColorHover(new Color(255, 102, 102));
            this.btnMarca.setColorPressed(new Color(255, 102, 102));

            this.btnCategoria.setColorNormal(new Color(255, 153, 153));
            this.btnCategoria.setColorHover(new Color(255, 102, 102));
            this.btnCategoria.setColorPressed(new Color(255, 102, 102));

            this.btnUnidadMedida.setColorNormal(new Color(255, 153, 153));
            this.btnUnidadMedida.setColorHover(new Color(255, 102, 102));
            this.btnUnidadMedida.setColorPressed(new Color(255, 102, 102));

            this.btnCompra.setColorNormal(new Color(255, 153, 153));
            this.btnCompra.setColorHover(new Color(255, 102, 102));
            this.btnCompra.setColorPressed(new Color(255, 102, 102));

            this.btnSalidaProducto.setColorNormal(new Color(255, 153, 153));
            this.btnSalidaProducto.setColorHover(new Color(255, 102, 102));
            this.btnSalidaProducto.setColorPressed(new Color(255, 102, 102));

            this.btnReporteDiario.setColorNormal(new Color(255, 153, 153));
            this.btnReporteDiario.setColorHover(new Color(255, 102, 102));
            this.btnReporteDiario.setColorPressed(new Color(255, 102, 102));
            
            this.btnReporteMensual.setColorNormal(new Color(255, 153, 153));
            this.btnReporteMensual.setColorHover(new Color(255, 102, 102));
            this.btnReporteMensual.setColorPressed(new Color(255, 102, 102));
            
            this.btnReporteSemanal.setColorNormal(new Color(255, 102, 102));
            this.btnReporteSemanal.setColorHover(new Color(255, 102, 102));
            this.btnReporteSemanal.setColorPressed(new Color(255, 102, 102));
        } else {
            this.btnReporteSemanal.setColorNormal(new Color(255, 153, 153));
            this.btnReporteSemanal.setColorHover(new Color(255, 102, 102));
            this.btnReporteSemanal.setColorPressed(new Color(255, 102, 102));
        }
    }//GEN-LAST:event_btnReporteSemanalActionPerformed

    private void btnReporteMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteMensualActionPerformed
        cambiar = new CambiaPanel(content, new panelReportMensual(), 336, 276);

        if (this.btnReporteMensual.isSelected()) {
            this.btnProducto.setColorNormal(new Color(255, 153, 153));
            this.btnProducto.setColorHover(new Color(255, 102, 102));
            this.btnProducto.setColorPressed(new Color(255, 102, 102));

            this.btnProveedor.setColorNormal(new Color(255, 153, 153));
            this.btnProveedor.setColorHover(new Color(255, 102, 102));
            this.btnProveedor.setColorPressed(new Color(255, 102, 102));

            this.btnMarca.setColorNormal(new Color(255, 153, 153));
            this.btnMarca.setColorHover(new Color(255, 102, 102));
            this.btnMarca.setColorPressed(new Color(255, 102, 102));

            this.btnCategoria.setColorNormal(new Color(255, 153, 153));
            this.btnCategoria.setColorHover(new Color(255, 102, 102));
            this.btnCategoria.setColorPressed(new Color(255, 102, 102));

            this.btnUnidadMedida.setColorNormal(new Color(255, 153, 153));
            this.btnUnidadMedida.setColorHover(new Color(255, 102, 102));
            this.btnUnidadMedida.setColorPressed(new Color(255, 102, 102));

            this.btnCompra.setColorNormal(new Color(255, 153, 153));
            this.btnCompra.setColorHover(new Color(255, 102, 102));
            this.btnCompra.setColorPressed(new Color(255, 102, 102));

            this.btnSalidaProducto.setColorNormal(new Color(255, 153, 153));
            this.btnSalidaProducto.setColorHover(new Color(255, 102, 102));
            this.btnSalidaProducto.setColorPressed(new Color(255, 102, 102));

            this.btnReporteDiario.setColorNormal(new Color(255, 153, 153));
            this.btnReporteDiario.setColorHover(new Color(255, 102, 102));
            this.btnReporteDiario.setColorPressed(new Color(255, 102, 102));
            
            this.btnReporteMensual.setColorNormal(new Color(255, 102, 102));
            this.btnReporteMensual.setColorHover(new Color(255, 102, 102));
            this.btnReporteMensual.setColorPressed(new Color(255, 102, 102));
            
            this.btnReporteSemanal.setColorNormal(new Color(255, 153, 153));
            this.btnReporteSemanal.setColorHover(new Color(255, 102, 102));
            this.btnReporteSemanal.setColorPressed(new Color(255, 102, 102));
        } else {
            this.btnReporteSemanal.setColorNormal(new Color(255, 153, 153));
            this.btnReporteSemanal.setColorHover(new Color(255, 102, 102));
            this.btnReporteSemanal.setColorPressed(new Color(255, 102, 102));
        }
    }//GEN-LAST:event_btnReporteMensualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    public void setObjP(Personal objP) {
        this.objP = objP;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnCategoria;
    private rsbuttom.RSButtonMetro btnCompra;
    private rsbuttom.RSButtonMetro btnMarca;
    private rsbuttom.RSButtonMetro btnProducto;
    private rsbuttom.RSButtonMetro btnProveedor;
    private rsbuttom.RSButtonMetro btnReporteDiario;
    private rsbuttom.RSButtonMetro btnReporteMensual;
    private rsbuttom.RSButtonMetro btnReporteSemanal;
    private rsbuttom.RSButtonMetro btnSalidaProducto;
    private rsbuttom.RSButtonMetro btnUnidadMedida;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
